import BaseAPI from "@/api/baseAPIClass"

class CadetAPI extends BaseAPI {}

export default function getCadetAPIInstance() {
  return new CadetAPI("cadet", {
    category: "",
    gender: "",
    last_name_rus__icontains: "",
    first_name_rus__icontains: "",
    last_name_bel__icontains: "",
    first_name_bel__icontains: "",
    last_name_en__icontains: "",
    first_name_en__icontains: "",
    date_of_birth__gte: "",
    date_of_birth__lte: "",
    place_of_birth__icontains: "",
    address_residence__icontains: "",
    address_registration__icontains: "",
    phone_number__icontains: "",
    personal_number_mvd__icontains: "",
    marital_status: "",
    passport_number__icontains: "",
    passport_issue_date__gte: "",
    passport_issue_date__lte: "",
    passport_validity_period__gte: "",
    passport_validity_period__lte: "",
    passport_issue_authority: "",
    identification_number__icontains: "",
    identification_number__gte: "",
    identification_number__lte: "",
    father_date_of_birth__gte: "",
    father_date_of_birth__lte: "",
    mother_date_of_birth__gte: "",
    mother_date_of_birth__lte: "",
    foreign_language_was: "",
    foreign_language_will_be: "",
    subdivision: "",
    group: "",
    academy_start_date__gte: "",
    academy_start_date__lte: "",
    academy_end_date__gte: "",
    academy_end_date__lte: "",
    specialization: "",
    direction_ord: "",
    current_rank: "",
    current_position: "",
    current_speciality: "",
    component_organ: "",
    entrance_category: "",
    arrived_from_go_rovd: "",
    social_status: "",
    region_for_medical_examination: "",
    military_office: "",
    extra_data__icontains: "",
  })
}
